import {
  Counters,
  Cars,
  Dinos,
  Nurse,
  LiveWeather,
  Store,
  BogotaTributte,
  Message,
  Travel,
  Movies
} from './images';

export const data = [
  {
    id: 1,
    image: Counters, 
    typeproyect: 'CLIENT',
    description: 'xxx',
    title: 'Counters App',
    github: 'https://github.com/NietoDeveloper/',
    demo: 'https://',
  },
  {
    id: 2,
    image: Store,
    typeproyect: 'CLIENT',
    title: 'Oil CBD Shop ',
    description: 'xxx',
    github: 'https://github.com/',
    demo: 'https://',
  },
  {
    id: 3,
    image: Nurse,
    title: 'Nurse Care',
    typeproyect: 'CLIENT',
    description: 'xxx',
    github: 'https://github.com/',
    demo: 'https:///',
  },
  {
    id: 4,
    image: Cars,
    typeproyect: 'CLIENT',
    title: 'Rent Cars',
    description: 'xxx',
    github: 'http://',
    demo: 'https://',
  },
  {
    id: 5,
    image: Dinos,
    typeproyect: 'PROYECT',
    title: 'Dino App',
    description: 'xxx',
    github: 'https://github.com/NietoDeveloper/DinoImages',
    demo: 'https://nietodeveloper.github.io/DinoImages',
  },
  {
    id: 6,
    image: BogotaTributte,
    typeproyect: 'PROYECT',
    title: 'Bogota City',
    description: 'xxx',
    github: 'https://github.com/NietoDeveloper/BogotaCityTributte',
    demo: 'https://nietodeveloper.github.io/BogotaCityTributte',
    
  },
  {
    id: 7,
    image: Travel,
    typeproyect: 'PROYECT',
    title: 'City Travel Info',
    description: 'xxx',
    github: 'https://github.com/NietoDeveloper/CityInfoTravel',
    demo: 'https://nietodeveloper.github.io/CityInfoTravel',
  },
  {
    id: 8,
    image: Message,
    typeproyect: 'PROYECT',
    title: 'Message App',
    description: 'xxx',
    github: 'https://https://github.com/NietoDeveloper/MessageToE-Mail',
    demo: 'https://nietodeveloper.github.io/MessageToE-Mail',
  },
  {
    id: 9,
    image: LiveWeather,
    typeproyect: 'PROYECT',
    title: 'Weather App',
    description: 'xxx',
    github: 'https://github.com/NietoDeveloper/CitysWeather',
    demo: 'https://nietodeveloper.github.io/CitysWeather/',
    
  },
  {
    id: 10,
    image: Movies,
    typeproyect: 'PROYECT',
    title: 'Search Movies',
    description: 'xxx',
    github: 'https://github.com/NietoDeveloper/SearchMovies',
    demo: 'https://nietodeveloper.github.io/SearchMovies',
  }
];
